- menu_name: "Services"

- name: "Contact"
  url: "https://us18.list-manage.com/contact-form?u=fd7a9519704f573e1bf7d96b7&form_id=a86dbc3f29b93759d8e7233e2b8ce118"
  title: "Contact"

- name: "RSS"
  url: "/feed.xml"
  title: "Subscribe to RSS Feed"

- name: "Atom"
  url: "/atom.xml"
  title: "Subscribe to Atom Feed"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
